/*
 * mbr88_gen_tplt.c — Generate mbr88_template.h from a compiled MBR binary
 *
 * Part of the mbr88 project.
 * MIT License — Copyright (c) 2025 Chris Piker
 *
 * AI disclosure:
 *   This code was generated with Anthropic Claude, which is an AI.  It is
 *   quite understandable that AI generated code may not be suitable for
 *   some projects.  If you prefer not to depend on AI generated (though
 *   human verified) code in your open source project, please do not
 *   include this file.
 *
 * Usage:
 *   mbr88_gen_tplt <mbr.bin> <mbr88_template.h>
 *
 * Reads a 512-byte MBR binary (typically mbr.bin produced by NASM or
 * ia16-elf-ld) and writes a C header file containing the byte array used
 * by mbr_patch.c for the -u (upgrade) flag.
 *
 * Intended to be run as part of the build process so that mbr88_template.h
 * is always in sync with the assembled binary.  See the project Makefile.
 *
 * Build (the generator itself runs on the build host, not on ELKS):
 *   gcc -std=c99 -Wall -o mbr88_gen_tplt mbr88_gen_tplt.c
 *
 * Typical Makefile usage:
 *   mbr88_template.h: mbr.bin mbr88_gen_tplt
 *       ./mbr88_gen_tplt mbr.bin mbr88_template.h
 *
 *   mbr.bin: mbr88_nasm.asm
 *       nasm -f bin mbr88_nasm.asm -o mbr.bin
 *
 *   mbr88_gen_tplt: mbr88_gen_tplt.c
 *       gcc -std=c99 -Wall -o mbr88_gen_tplt mbr88_gen_tplt.c
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define MBR_SIZE         512
#define BYTES_PER_ROW    12

/* Known offsets — these are verified at runtime against the binary */
#define SIG_OFFSET       0x1B8
#define SIG_LEN          5
#define VER_OFFSET       0x1BD
#define BOOTSIG_OFFSET   0x1FE

static const unsigned char EXPECTED_SIG[SIG_LEN] = {'m','b','r','8','8'};

int main(int argc, char *argv[])
{
    FILE          *fin, *fout;
    unsigned char  buf[MBR_SIZE];
    int            i, row;
    const char    *inpath, *outpath;

    if (argc != 3) {
        fprintf(stderr, "Usage: mbr88_gen_tplt <mbr.bin> <mbr88_template.h>\n");
        return 1;
    }

    inpath  = argv[1];
    outpath = argv[2];

    /* Read the binary */
    fin = fopen(inpath, "rb");
    if (!fin) {
        perror(inpath);
        return 1;
    }
    if (fread(buf, 1, MBR_SIZE, fin) != MBR_SIZE) {
        fprintf(stderr, "Error: '%s' must be exactly %d bytes.\n",
                inpath, MBR_SIZE);
        fclose(fin);
        return 1;
    }
    fclose(fin);

    /* Validate boot signature */
    if (buf[BOOTSIG_OFFSET] != 0x55 || buf[BOOTSIG_OFFSET + 1] != 0xAA) {
        fprintf(stderr, "Error: '%s' has no 55 AA boot signature at 0x1FE.\n",
                inpath);
        return 1;
    }

    /* Validate mbr88 signature */
    if (memcmp(buf + SIG_OFFSET, EXPECTED_SIG, SIG_LEN) != 0) {
        fprintf(stderr,
                "Error: '%s' does not contain the 'mbr88' signature at 0x%03X.\n"
                "       This tool only generates templates from mbr88 binaries.\n",
                inpath, SIG_OFFSET);
        return 1;
    }

    /* Report version from binary */
    {
        unsigned char ver = buf[VER_OFFSET];
        fprintf(stderr, "mbr88 v%d.%d detected in '%s'.\n",
                (ver >> 4) & 0x0F, ver & 0x0F, inpath);
    }

    /* Write the header file */
    fout = fopen(outpath, "w");
    if (!fout) {
        perror(outpath);
        return 1;
    }

    fprintf(fout,
        "/*\n"
        " * mbr88_template.h — Blank mbr88 boot record as a C byte array\n"
        " *\n"
        " * This file is part of the mbr88 project.\n"
        " * MIT License — Copyright (c) 2025 Chris Piker\n"
        " *\n"
        " * DO NOT EDIT BY HAND.  This file is generated by mbr88_gen_tplt.c:\n"
        " *   ./mbr88_gen_tplt mbr.bin mbr88_template.h\n"
        " *\n"
        " * To regenerate after modifying mbr88_nasm.asm or mbr88_gas.s:\n"
        " *   nasm -f bin mbr88_nasm.asm -o mbr.bin\n"
        " *   ./mbr88_gen_tplt mbr.bin mbr88_template.h\n"
        " *\n"
        " * mbr_patch.c uses this template for the -u (upgrade) flag.\n"
        " * The signature 'mbr88' is at offset 0x%03X; version byte at 0x%03X.\n"
        " */\n"
        "\n"
        "#ifndef MBR88_TEMPLATE_H\n"
        "#define MBR88_TEMPLATE_H\n"
        "\n"
        "#define MBR88_TEMPLATE_SIZE  %d\n"
        "#define MBR88_SIG_OFFSET     0x%03X   /* offset of 'mbr88' signature */\n"
        "#define MBR88_SIG_LEN        %d       /* length of signature (no null) */\n"
        "#define MBR88_VER_OFFSET     0x%03X   /* version byte: high=major, low=minor */\n"
        "\n"
        "static const unsigned char MBR88_TEMPLATE[MBR88_TEMPLATE_SIZE] = {\n",
        SIG_OFFSET, VER_OFFSET,
        MBR_SIZE,
        SIG_OFFSET, SIG_LEN, VER_OFFSET);

    for (row = 0; row < MBR_SIZE; row += BYTES_PER_ROW) {
        fprintf(fout, "    ");
        for (i = row; i < row + BYTES_PER_ROW && i < MBR_SIZE; i++) {
            int last = (i == MBR_SIZE - 1);
            fprintf(fout, "0x%02X%s", buf[i], last ? "" : ",");
            if (!last && (i + 1) % BYTES_PER_ROW != 0)
                fprintf(fout, " ");
        }
        fprintf(fout, "\n");
    }

    fprintf(fout,
        "};\n"
        "\n"
        "#endif /* MBR88_TEMPLATE_H */\n");

    fclose(fout);
    fprintf(stderr, "Written: %s\n", outpath);
    return 0;
}
